version,user_name,date,time,product,is_success,num_files_created,missing_files_found,files_added_to_testng,error_msg,test_analyzed,ng_files_found,non_ng_files_found,total_files_with_descrepancies,total_files_without_descrepancies,passed_tests_with_no_ng_path,passed_tests_found_with_no_change,ng_files_overwritten,files_with_new_descrepencies
1,zalmanr,07/02/2024,11:24:04,Refactor_Tests,TRUE,21,,,,22,7,15,,,,,,
1,yaels,07/02/2024,11:26:31,Refactor_Tests,TRUE,0,,,,5,4,1,,,,,,
1,zalmanr,07/02/2024,11:26:37,Refactor_Tests,TRUE,0,,,,22,7,15,,,,,,
1,ilanb,07/02/2024,11:29:44,Test_List_Compare,TRUE,,10,,,,,,,,,,
1,yaels,07/02/2024,11:30:39,Test_List_Compare,TRUE,,3747,,,,,,,,,,
1,ilanb,07/02/2024,11:32:48,Test_List_Compare,TRUE,,9,,,,,,,,,,
1,yaels,07/02/2024,11:33:13,Refactor_Tests,TRUE,5,,,,5,4,1,,,,,,
1,ronif,07/02/2024,11:38:00,Refactor_Tests,TRUE,0,,,,17,17,0,,,,,,
1,rona,07/02/2024,11:51:55,Refactor_Tests,TRUE,10,,,,10,9,1,,,,,,
1,rona,07/02/2024,11:53:37,Refactor_Tests,TRUE,0,,,,10,9,1,,,,,,
1,ilanb,07/02/2024,12:23:25,Test_List_Compare,TRUE,,13,,,,,,,,,,
1,hadark,07/02/2024,13:52:11,Refactor_Tests,TRUE,2,,,,2,1,1,,,,,,
1,hadark,07/02/2024,14:00:46,Refactor_Tests,TRUE,0,,,,107,47,60,,,,,,
1,yaels,07/02/2024,14:04:43,Test_List_Compare,TRUE,,0,,,,,,,,,,
1,yaels,07/02/2024,14:05:30,Test_List_Compare,TRUE,,0,,,,,,,,,,
1,idob,08/02/2024,10:10:38,Refactor_Tests,TRUE,1,,,,,,,,,,,
1.0,idob,2024-02-11,11:47:09,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-11,17:39:44,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,08:35:39,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,08:49:54,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,08:54:50,Refactor_Tests,True,3,,,,,,,,,,
1.0,idob,2024-02-12,09:39:57,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,10:03:59,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,10:10:29,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,10:20:04,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,11:07:01,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,11:18:14,Refactor_Tests,True,1,,,,,,,,,,
1.0,idob,2024-02-12,11:52:57,Refactor_Tests,True,1,,,,,,,,,,
1.4,davidbe,2024-02-12,13:08:43,Test_List_Compare,True,,4619,,,4741,,,,,,,,
1.4,idob,2024-02-12,13:43:15,Refactor_Tests,True,1,,,,2,1,1,,,,,,
1.4,idob,2024-02-12,14:11:27,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-12,14:46:23,Refactor_Tests,True,0,,,,75,30,45,,,,,,
1.4,idob,2024-02-12,15:03:38,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,idob,2024-02-12,15:24:17,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-12,15:51:48,Refactor_Tests,True,0,,,,10,1,9,,,,,,
1.4,idob,2024-02-12,16:05:01,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-12,16:30:02,Refactor_Tests,True,3,,,,3,0,3,,,,,,
1.4,yaels,2024-02-12,16:33:28,Refactor_Tests,True,0,,,,3,0,3,,,,,,
1.4,yaels,2024-02-12,16:33:38,Refactor_Tests,True,5,,,,5,2,3,,,,,,
1.4,yaels,2024-02-13,08:34:35,Refactor_Tests,True,5,,,,5,2,3,,,,,,
1.4,idob,2024-02-13,08:35:56,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-13,09:34:18,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-13,10:27:54,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-13,11:26:05,Refactor_Tests,True,5,,,,5,0,5,,,,,,
1.4,yaels,2024-02-13,15:05:51,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-13,15:16:19,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-13,15:17:54,Refactor_Tests,True,0,,,,1,0,1,,,,,,
1.4,yaels,2024-02-13,16:36:38,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,idob,2024-02-14,10:50:11,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-14,11:04:27,Refactor_Tests,True,0,,,,73,38,35,,,,,,
1.4,davidbe,2024-02-14,12:46:38,Refactor_Tests,True,1,,,,13,2,11,,,,,,
1.4,yaels,2024-02-14,13:59:07,Refactor_Tests,True,0,,,,1,1,0,,,,,,
1.4,yaels,2024-02-14,13:59:16,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-14,14:39:17,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-14,14:51:40,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-14,15:28:30,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-15,08:28:16,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-15,09:06:43,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,10:09:53,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-15,10:51:41,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-15,12:34:53,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,13:01:35,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,13:20:56,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,13:55:25,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,14:13:54,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,15:31:47,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,16:11:05,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,16:43:42,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-15,16:50:52,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-15,17:04:30,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-15,17:05:37,Refactor_Tests,True,0,,,,1,1,0,,,,,,
1.4,yaels,2024-02-16,10:27:49,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-16,10:54:30,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-16,11:21:54,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-16,11:28:17,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-16,11:35:17,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,09:00:20,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,09:18:37,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-18,10:54:08,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,10:58:36,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-18,11:10:37,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-18,11:15:35,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-18,11:21:15,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,11:30:22,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,11:31:06,Refactor_Tests,True,0,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,11:51:13,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-18,12:01:44,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,hadark,2024-02-18,12:54:31,Refactor_Tests,True,0,,,,71,32,39,,,,,,
1.4,yaels,2024-02-18,13:51:26,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-18,15:02:33,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-18,16:47:24,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,10:42:58,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,11:25:10,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,12:22:51,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,13:21:53,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,13:49:16,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,13:55:34,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,14:04:48,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:05:41,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,14:12:41,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:13:54,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:15:40,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,14:18:12,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,14:22:07,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:29:52,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,14:36:22,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:39:18,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:44:20,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,14:50:18,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,14:52:58,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,15:16:41,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-19,15:42:45,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,idob,2024-02-19,16:05:22,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,16:10:56,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.5,davidbe,2024-02-19,16:40:23,Discrepancy_Tracker,True,,,,,778,,,398,380,C:\Users\davidbe\AppData\Local\RefactoringAssistant\output\output_of_discrepancy_tracker\tests_marked_as_passed_but_missing_ng_path.txt,,0,
1.5,davidbe,2024-02-19,16:41:06,Discrepancy_Tracker,True,,,,,39,,,,,,,,5
1.4,yaels,2024-02-19,16:41:32,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-19,16:44:19,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,16:51:58,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-19,16:53:55,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-19,17:47:15,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,idob,2024-02-19,18:06:00,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-19,18:16:20,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.5,davidbe,2024-02-19,19:32:19,Discrepancy_Tracker,True,,,,,778,,,398,380,C:\Users\davidbe\AppData\Local\RefactoringAssistant\output\output_of_discrepancy_tracker\tests_marked_as_passed_but_missing_ng_path.txt,,66,
1.4,yaels,2024-02-20,07:59:24,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-20,08:13:35,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-20,09:11:25,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-20,10:56:02,Refactor_Tests,True,2,,,,2,2,0,,,,,,
1.4,yaels,2024-02-20,11:33:34,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-20,11:44:11,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-20,13:46:45,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-20,14:15:00,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-20,14:17:35,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-20,14:49:19,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-20,14:57:54,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-20,15:14:02,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-20,15:36:07,Refactor_Tests,True,4,,,,4,4,0,,,,,,
1.4,yaels,2024-02-20,15:38:05,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-20,15:45:30,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-20,16:31:23,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-20,17:15:00,Refactor_Tests,True,0,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-20,17:27:25,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-20,17:59:32,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-21,10:16:26,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-21,10:20:59,Refactor_Tests,True,0,,,,5,4,1,,,,,,
1.4,davidbe,2024-02-21,10:22:38,Refactor_Tests,True,4,,,,4,4,0,,,,,,
1.4,idob,2024-02-21,11:36:19,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,idob,2024-02-21,11:45:03,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,idob,2024-02-21,12:16:37,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-21,12:46:17,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-21,16:00:09,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-22,11:00:31,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-22,12:16:38,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,idob,2024-02-22,12:18:55,Refactor_Tests,True,2,,,,2,0,2,,,,,,
1.4,yaels,2024-02-22,12:36:22,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-22,13:33:49,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-22,15:01:19,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-22,15:14:24,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-22,16:04:01,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-25,08:40:04,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-25,09:46:47,Refactor_Tests,True,0,,,,1,1,0,,,,,,
1.4,yaels,2024-02-25,09:47:54,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-25,09:49:21,Refactor_Tests,True,0,,,,1,1,0,,,,,,
1.4,rona,2024-02-25,11:38:00,Refactor_Tests,True,0,,,,8,7,1,,,,,,
1.4,yaels,2024-02-25,12:53:15,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-26,08:32:12,Discrepancy_Tracker,True,,,,,918,,,545,373,C:\Users\davidbe\AppData\Local\RefactoringAssistant\output\tests_marked_as_passed_but_missing_ng_path.txt,,,
1.4,rona,2024-02-26,11:12:38,Refactor_Tests,True,0,,,,12,10,2,,,,,,
1.5,davidbe,2024-02-26,13:47:16,Test_List_Compare,True,,252,,,2451,,,,,,,,
1.4,hadark,2024-02-26,14:11:50,Refactor_Tests,True,61,,,,77,44,33,,,,,,
1.4,shaharh,2024-02-26,16:10:21,Refactor_Tests,True,0,,,,134,85,49,,,,,,
1.4,yaels,2024-02-28,08:16:37,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,shaharh,2024-02-28,10:11:14,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 46, in init_params
  File ""src\gen_files\gen_scripts.py"", line 70, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.4,davidbe,2024-02-28,10:14:32,Refactor_Tests,True,0,,,,13,12,1,,,,,,
1.4,yaels,2024-02-28,11:05:49,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-28,12:46:55,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,davidbe,2024-02-28,13:04:05,Refactor_Tests,True,0,,,,50,38,12,,,,,,
1.4,davidbe,2024-02-28,14:15:31,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,davidbe,2024-02-28,14:51:06,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-29,08:38:49,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-29,10:18:52,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-29,14:56:14,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-29,15:05:51,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-02-29,16:33:45,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-02-29,17:08:48,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-03-03,08:12:46,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-03-03,09:26:30,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-03-03,10:04:09,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-03-03,10:14:16,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-03-03,13:19:51,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,U6066742,2024-03-03,16:08:11,Refactor_Tests,True,11,,,,12,9,3,,,,,,
1.5,davidbe,2024-03-04,10:35:23,Discrepancy_Tracker,True,,,,,981,,,460,521,59,,,
1.5,davidbe,2024-03-04,10:38:43,Discrepancy_Tracker,True,,,,,1011,,,489,522,30,,,
1.7,zalmanr,2024-03-04,14:01:18,Refactor_Tests,True,41,,,,41,0,41,,,,,,
1.7,davidbe,2024-03-04,14:02:14,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,davidbe,2024-03-04,14:08:37,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,davidbe,2024-03-04,14:23:33,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.4,yaels,2024-03-04,16:16:03,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.4,yaels,2024-03-05,09:19:13,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,rona,2024-03-05,09:52:11,Refactor_Tests,True,14,,,,14,7,7,,,,,,
1.4,yaels,2024-03-06,12:18:02,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,davidbe,2024-03-06,13:42:25,Refactor_Tests,True,1,,,,1,0,1,,,,,,
1.7,davidbe,2024-03-06,15:07:44,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,davidbe,2024-03-06,15:25:47,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,davidbe,2024-03-06,16:10:41,Refactor_Tests,True,0,,,,64,4,60,,,,,,
1.7,davidbe,2024-03-06,16:26:38,Refactor_Tests,True,0,,,,168,9,159,,,,,,
1.7,davidbe,2024-03-06,16:30:25,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,yaels,2024-03-07,09:34:26,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,yaels,2024-03-07,10:30:40,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,zalmanr,2024-03-07,11:42:55,Refactor_Tests,True,0,,,,19,9,10,,,,,,
1.7,zalmanr,2024-03-07,11:47:58,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:48:02,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:48:39,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:48:49,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:49:07,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:49:11,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:49:12,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,11:49:13,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,12:15:30,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,12:15:50,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,12:34:51,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,12:35:09,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\zalmanr\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,zalmanr,2024-03-07,12:42:40,Refactor_Tests,True,16,,,,16,8,8,,,,,,
1.7,zalmanr,2024-03-07,12:43:09,Refactor_Tests,True,17,,,,20,13,7,,,,,,
1.7,zalmanr,2024-03-07,13:11:18,Refactor_Tests,True,14,,,,16,12,4,,,,,,
1.7,zalmanr,2024-03-07,13:15:08,Refactor_Tests,True,11,,,,19,16,3,,,,,,
1.7,zalmanr,2024-03-07,13:22:28,Refactor_Tests,True,49,,,,112,81,31,,,,,,
1.7,hadark,2024-03-07,13:26:17,Refactor_Tests,True,0,,,,2,0,2,,,,,,
1.7,hadark,2024-03-07,13:37:12,Refactor_Tests,True,0,,,,26,19,7,,,,,,
1.7,zalmanr,2024-03-07,15:20:06,Refactor_Tests,True,1,,,,105,82,23,,,,,,
1.7,zalmanr,2024-03-10,09:44:26,Refactor_Tests,True,0,,,,105,82,23,,,,,,
1.7,davidbe,2024-03-11,10:32:27,Discrepancy_Tracker,True,,,,,1174,,,568,606,31,,,
1.7,shaharh,2024-03-11,17:25:34,Test_List_Compare,True,,0,,,87,,,,,,,,
1.7,yaels,2024-03-12,09:06:06,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,shaharh,2024-03-12,14:07:04,Refactor_Tests,True,0,,,,87,78,9,,,,,,
1.7,shaharh,2024-03-12,14:27:00,Refactor_Tests,True,0,,,,10,4,6,,,,,,
1.7,yaels,2024-03-12,15:11:40,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,shaharh,2024-03-12,15:26:11,Refactor_Tests,True,0,,,,83,78,5,,,,,,
1.7,yaels,2024-03-12,15:35:56,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,yaels,2024-03-12,16:42:36,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,davidbe,2024-03-13,09:00:35,Discrepancy_Tracker,True,,,,,1224,,,606,618,52,,,
1.7,rona,2024-03-13,10:17:57,Refactor_Tests,True,5,,,,6,3,3,,,,,,
1.7,shaharh,2024-03-13,10:37:43,Refactor_Tests,True,0,,,,81,76,5,,,,,,
1.7,shaharh,2024-03-13,12:47:00,Refactor_Tests,True,0,,,,10,4,6,,,,,,
1.7,shaharh,2024-03-13,12:48:26,Refactor_Tests,True,0,,,,80,75,5,,,,,,
1.7,shaharh,2024-03-13,12:52:09,Refactor_Tests,True,0,,,,4,0,4,,,,,,
1.7,shaharh,2024-03-13,12:52:54,Refactor_Tests,True,0,,,,2,0,2,,,,,,
1.7,shaharh,2024-03-13,14:06:08,Refactor_Tests,True,0,,,,77,73,4,,,,,,
1.7,shaharh,2024-03-13,17:11:06,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,shaharh,2024-03-13,17:11:46,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,shaharh,2024-03-13,17:11:57,Refactor_Tests,False,,,,"An Error occured: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
Traceback:
Traceback (most recent call last):
  File ""src\main_refactoring_assistant\main-RefactoringAssistant.py"", line 44, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 12, in main_script
  File ""src\refactor_tests\main_refactor_tests.py"", line 47, in init_params
  File ""src\gen_files\gen_scripts.py"", line 71, in clear_create_dir
  File ""os.py"", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\shaharh\\AppData\\Local\\RefactoringAssistant\\output'
",,,,,,,,,
1.7,yaels,2024-03-14,13:57:03,Refactor_Tests,True,1,,,,1,1,0,,,,,,
1.7,yaels,2024-03-17,08:19:49,Refactor_Tests,True,1,,,,1,1,0,,,,,,
